export const FAKE_LIST_MEDICINE = [
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 736,
        name: "Thuốc tiêu hoá & gan mật",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 804,
        name: "Thuốc dạ dày",
        parentName: "Thuốc tiêu hoá & gan mật",
        level: 3,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat/thuoc-da-day",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      "<p>Thuốc Pymenospain được sản xuất bởi Công ty cổ phần Pymepharco, có thành phần chính là Drotaverin HCI. Thuốc\u00A0 Pymenospain được chỉ định trong các trường hợp co thắt dạ dày - ruột; hội chứng ruột bị kích thích; cơn đau quặn mật và các co thắt đường mật; cơn đau quặn thận và các co thắt đường niệu - sinh dục; các co thắt tử cung; co thắt dạ dày - ruột do loét, táo bón co thắt.</p>\n\n<p>Thuốc Pymenospain được bào chế dưới dạng viên nén; hộp 05 vỉ x 10 viên hoặc lọ 200 viên.</p>",
    isPublish: true,
    prices: [
      {
        id: 35382,
        measureUnitCode: 7,
        measureUnitName: "Lọ",
        isSellDefault: false,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 29,
        isInventory: false,
        level: 1,
        productSpecs: null,
      },
      {
        id: 35381,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: true,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 29,
        isInventory: false,
        level: 3,
        productSpecs: null,
      },
    ],
    sku: "00028069",
    webName: "Thuốc Pymenospain Pymepharco chống co thắt dạ dày - ruột (200 viên)",
    name: "PYMENOSPAIN 40MG PYMEPHARCO 200V",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00028069_pymenospain_40mg_pymepharco_200v_1914_60a5_large_6a12fd89e1.jpg",
    slug: "thuoc/pymenospain-40mg-pymepharco-200v-28210.html",
    brand: "Pymepharco",
    productRanking: 0.5,
    displayCode: 3,
    price: {
      id: 35381,
      measureUnitCode: 8,
      measureUnitName: "Viên",
      isSellDefault: true,
      price: null,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 29,
      isInventory: false,
    },
    specification: "Lọ 200 viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 736,
        name: "Thuốc tiêu hoá & gan mật",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 806,
        name: "Thuốc trị tiêu chảy",
        parentName: "Thuốc tiêu hoá & gan mật",
        level: 3,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat/thuoc-tri-tieu-chay",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      "<p>Smecta là thuốc điều trị tiêu chảy theo cơ chế hấp phụ, với hoạt chất chính Diosmectit 3g, tá dược: Glucose monohydrate, natri saccharin, hương cam*, hương vani* . Đóng gói thành hộp chứa 30 gói bột pha hỗn dịch uống.</p>",
    isPublish: true,
    prices: [
      {
        id: 9885,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: false,
        price: 123000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
      {
        id: 9884,
        measureUnitCode: 14,
        measureUnitName: "Gói",
        isSellDefault: true,
        price: 4100.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
    ],
    sku: "00006780",
    webName: "Thuốc bột pha hỗn dịch uống Smecta vị cam điều trị tiêu chảy (30 gói x 3g)",
    name: "SMECTA ORANGE 3G IPSEN 30 GÓI",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/IMG_1718_1ac3c4cfae.jpg",
    slug: "thuoc/smecta-2236.html",
    brand: "Ipsen",
    productRanking: 0,
    displayCode: 1,
    price: {
      id: 9884,
      measureUnitCode: 14,
      measureUnitName: "Gói",
      isSellDefault: true,
      price: 4100.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 30 Gói x 3g",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 10,
        name: "Thuốc dị ứng",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-di-ung",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 750,
        name: "Thuốc chống dị ứng",
        parentName: "Thuốc dị ứng",
        level: 3,
        slug: "thuoc/thuoc-di-ung/thuoc-chong-di-ung",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p>Thuốc Telfast HD 180mg được sản xuất bởi công ty Cổ Phần Sanofi Việt Nam. Telfast HD 180mg được chỉ định để điều trị viêm mũi dị ứng theo mùa và các biểu hiện ngoài da không biến chứng của mày đay vô căn mạn tính ở người lớn và trẻ em từ 12 tuổi trở lên.</p><p>Viên nén bao phim, màu hồng nhạt, hình thuôn dài, hai mặt lồi, một mặt có khắc hình 8, mặt kia khắc số "018".&nbsp;</p>',
    isPublish: true,
    prices: [
      {
        id: 10516,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: false,
        price: 7799.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
      {
        id: 10517,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: 77990.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
      {
        id: 10518,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: true,
        price: 77990.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00007223",
    webName: "Thuốc Telfast HD 180mg Sanofi điều trị viêm mũi dị ứng, mày đay (1 vỉ x 10 viên)",
    name: "TELFAST 180MG SANOFI 1X10",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/IMG_1251_828ef725ee.jpg",
    slug: "thuoc/telfast-180mg-2051.html",
    brand: "Sanofi",
    productRanking: 0,
    displayCode: 1,
    price: {
      id: 10518,
      measureUnitCode: 1,
      measureUnitName: "Hộp",
      isSellDefault: true,
      price: 77990.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 1 Vỉ x 10 Viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 727,
        name: "Thuốc bổ & vitamin",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-bo-and-vitamin",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 752,
        name: "Thuốc bổ",
        parentName: "Thuốc bổ & vitamin",
        level: 3,
        slug: "thuoc/thuoc-bo-and-vitamin/thuoc-bo",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      "<p>Farzincol của công ty cổ phần dược phẩm dược liệu Pharmedic, thành phần chính kẽm gluconat 70 mg (tương đương 10 mg kẽm), là thuốc dùng để điều trị bổ sung kẽm vào chế độ ăn trong các trường hợp: Bệnh còi xương, chậm tăng trưởng ở trẻ em. Phụ nữ mang thai và bà mẹ đang cho con bú. Chế độ ăn thiếu cân bằng hoặc kiêng ăn. Nuôi ăn lâu dài qua đường tĩnh mạch. Tiêu chảy cấp và mãn tính. Điều trị thiếu kẽm: Thiếu kẽm nhẹ và vừa trong các trường hợp: Suy dinh dưỡng nhẹ và vừa. Rối loạn đường tiêu hóa: Chán ăn, chậm tiêu, táo bón nhẹ, buồn nôn và nôn khi mang thai. Khó ngủ, mất ngủ, trẻ khóc đêm, suy nhược, nhức đầu...</p>",
    isPublish: true,
    prices: [
      {
        id: 4018,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: true,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
      {
        id: 4020,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: false,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
      {
        id: 4019,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
    ],
    sku: "00002990",
    webName: "Thuốc Farzincol Pharmedic điều trị thiếu kẽm (10 vỉ x 10 viên)",
    name: "FARZINCOL 10MG PHARMEDIC 10X10",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00002990_farzincol_10mg_6963_62a6_large_35ccff372c.jpg",
    slug: "thuoc/farzincol-10mg-3786.html",
    brand: "Pharmedic",
    productRanking: 0,
    displayCode: 2,
    price: {
      id: 4018,
      measureUnitCode: 8,
      measureUnitName: "Viên",
      isSellDefault: true,
      price: null,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 10 vỉ x 10 viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 736,
        name: "Thuốc tiêu hoá & gan mật",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 807,
        name: "Thuốc tiêu hoá",
        parentName: "Thuốc tiêu hoá & gan mật",
        level: 3,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat/thuoc-tieu-hoa",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p style="text-align:justify;">Enterogermina là sản phẩm của nhà sản xuất Sanofi (Italia), có thành phần chính bào tử kháng đa kháng sinh Bacillus clausii.</p><p style="text-align:justify;">Thuốc được dùng để điều trị và phòng ngừa rối loạn hệ vi khuẩn đường ruột và bệnh lý kém hấp thu vitamin nội sinh, điều trị hỗ trợ để phục hồi hệ vi khuẩn đường ruột bị ảnh hưởng khi dùng thuốc kháng sinh hoặc hóa trị liệu, rối loạn tiêu hóa cấp và mạn tính ở trẻ em do nhiễm độc hoặc rối loạn hệ vi khuẩn&nbsp;đường ruột và kém hấp thu vitamin.</p>',
    isPublish: true,
    prices: [
      {
        id: 3736,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: 80000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
      {
        id: 3737,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: true,
        price: 160000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
      {
        id: 3735,
        measureUnitCode: 15,
        measureUnitName: "Ống",
        isSellDefault: false,
        price: 8000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
    ],
    sku: "00002814",
    webName: "Men vi sinh Enterogermina 2 tỷ/5ml điều trị rối loạn tiêu hóa (2 vỉ x 10 ống)",
    name: "ENTEROGERMINA 2 TỶ SANOFI 2X10 5ML",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00002814_enterogemina_5ml_sanofi_20_ong_5650_60fb_large_25c7916c1f.jpg",
    slug: "thuoc/enterogemina-5ml-sanofi-20-ong-17315.html",
    brand: "Sanofi",
    productRanking: 0,
    displayCode: 1,
    price: {
      id: 3737,
      measureUnitCode: 1,
      measureUnitName: "Hộp",
      isSellDefault: true,
      price: 160000.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 2 Vỉ x 10 Ống x 5ml",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 33,
        name: "Thuốc da liễu",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-da-lieu",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 370,
        name: "Thuốc bôi ngoài da",
        parentName: "Thuốc da liễu",
        level: 3,
        slug: "thuoc/thuoc-da-lieu/thuoc-boi-ngoai-da",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      "<p>Kem trị mụn Differin 0.1% từ thương hiệu Galderma, được sản xuất bởi Laboratoires Galderma- Pháp. Differin 0.1% thuộc nhóm thuốc điều trị bệnh da liễu, được sử dụng điều trị mụn trứng cá bao gồm mụn nhân, mụn li ti, mụn mủ ở các vị trí mặt, ngực, lưng.</p>",
    isPublish: true,
    prices: [
      {
        id: 3140,
        measureUnitCode: 2,
        measureUnitName: "Tuýp",
        isSellDefault: true,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00002441",
    webName: "Kem Differin Galderma điều trị mụn trứng cá (30g)",
    name: "DIFFERIN 0.1% CREAM GALDERMA 30G",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00002441_differin_0130mg_1565_5c87_large_080d740339.jpg",
    slug: "thuoc/differin-0130mg-17372.html",
    brand: "Galderma",
    productRanking: 0,
    displayCode: 2,
    price: {
      id: 3140,
      measureUnitCode: 2,
      measureUnitName: "Tuýp",
      isSellDefault: true,
      price: null,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Tuýp",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 33,
        name: "Thuốc da liễu",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-da-lieu",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 361,
        name: "Thuốc trị mụn",
        parentName: "Thuốc da liễu",
        level: 3,
        slug: "thuoc/thuoc-da-lieu/thuoc-tri-mun",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p>Kem bôi Klenzit MS 15g là <a href="https://nhathuoclongchau.com.vn/thuoc/thuoc-da-lieu/thuoc-tri-mun">thuốc trị mụn</a> do Công ty&nbsp;Glenmark Pharmaceuticals sản xuất, nhập khẩu trực tiếp từ Ấn Độ, với&nbsp;thành phần chính adapalen ở dạng hệ cung cấp thuốc vi xốp, được dùng để điều trị cho bệnh nhân bị bệnh&nbsp;trứng cá.</p><p>Sản phẩm được bào chế dạng gel bôi ngoài da, tuýp 15 g tiện lợi. Trong quá trình sử dụng, cần lưu ý phân biệt hai loại Klenzit MS và Klenzit C. Kem trị mụn Klenzit MS chỉ chứa hoạt chất Adapalene ở dạng vi cầu giúp kiểm soát các hoạt chất thấm vào da, từ đó làm giảm các kích ứng không cần thiết lên da.</p>',
    isPublish: true,
    prices: [
      {
        id: 5832,
        measureUnitCode: 2,
        measureUnitName: "Tuýp",
        isSellDefault: true,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00004206",
    webName: "Gel bôi da Klenzit MS điều trị mụn trứng cá (15g)",
    name: "KLENZIT GLENMARK 15G",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/IMG_4396_43605a2469.jpg",
    slug: "thuoc/klenzit-15g-3330.html",
    brand: "Glenmark",
    productRanking: 0,
    displayCode: 2,
    price: {
      id: 5832,
      measureUnitCode: 2,
      measureUnitName: "Tuýp",
      isSellDefault: true,
      price: null,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Tuýp",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 736,
        name: "Thuốc tiêu hoá & gan mật",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 804,
        name: "Thuốc dạ dày",
        parentName: "Thuốc tiêu hoá & gan mật",
        level: 3,
        slug: "thuoc/thuoc-tieu-hoa-and-gan-mat/thuoc-da-day",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      "<p><strong>Thuốc Kremil-S</strong> là sản phẩm của <i>United International Pharma</i>, có thành phần chính là Aluminum Hydroxide; Magnesium Hydroxide; Simethicone làm giảm các triệu chứng như khó tiêu, ợ nóng, đầy hơi.</p>",
    isPublish: true,
    prices: [
      {
        id: 5884,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: false,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
      {
        id: 5883,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
      {
        id: 5882,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: true,
        price: null,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
    ],
    sku: "00004244",
    webName:
      "Viên nhai Kremil-S United điều trị đau dạ dày, giảm nóng rát dạ dày, ợ nóng, ợ chua (10 vỉ x 10 viên)",
    name: "KREMIL-S UNITED 10X10",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/IMG_2392_57bc68480d.jpg",
    slug: "thuoc/kremils-s-3315.html",
    brand: "United",
    productRanking: 2.3549653,
    displayCode: 2,
    price: {
      id: 5882,
      measureUnitCode: 8,
      measureUnitName: "Viên",
      isSellDefault: true,
      price: null,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 10 Vỉ x 10 Viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 729,
        name: "Thuốc giảm đau, hạ sốt, kháng viêm",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-giam-dau-ha-sot-khang-viem",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 768,
        name: "Thuốc giảm đau hạ sốt",
        parentName: "Thuốc giảm đau, hạ sốt, kháng viêm",
        level: 3,
        slug: "thuoc/thuoc-giam-dau-ha-sot-khang-viem/thuoc-giam-dau-ha-sot",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p>Viên sủi <a href="https://nhathuoclongchau.com.vn/thuoc/efferalgan-500mg-1620.html">Efferalgan 500mg</a> của Công ty UPSA SAS, thành phần chính paracetamol hay còn gọi là <a href="https://nhathuoclongchau.com.vn/thanh-phan/acetaminophen">acetaminophen</a>, có hai tác dụng chính là giảm đau và hạ sốt. Thuốc Efferalgan 500mg thường được dùng để điều trị giảm các cơn đau thông thường (đau đầu, đau răng, <a href="https://nhathuoclongchau.com.vn/benh/dau-xuong-khop-1303.html">đau nhức xương khớp</a>,…) hoặc được sử dụng để hạ sốt.</p>',
    isPublish: true,
    prices: [
      {
        id: 12309,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: false,
        price: 2999.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
      {
        id: 12310,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: 11998.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
      {
        id: 12311,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: true,
        price: 47990.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00008350",
    webName: "Viên sủi Efferalgan 500mg UPSA SAS giảm đau, hạ sốt (4 vỉ x 4 viên)",
    name: "EFFERALGAN 500MG 4X4",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/eferalgan_1_f94f787f4f.jpg",
    slug: "thuoc/efferalgan-500mg-1620.html",
    brand: "Upsa Sas",
    productRanking: 0,
    displayCode: 1,
    price: {
      id: 12311,
      measureUnitCode: 1,
      measureUnitName: "Hộp",
      isSellDefault: true,
      price: 47990.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 4 Vỉ x 4 Viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 727,
        name: "Thuốc bổ & vitamin",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-bo-and-vitamin",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 752,
        name: "Thuốc bổ",
        parentName: "Thuốc bổ & vitamin",
        level: 3,
        slug: "thuoc/thuoc-bo-and-vitamin/thuoc-bo",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p>Viên sủi <a href="https://nhathuoclongchau.com.vn/thuoc/berocca-1515.html">Berocca</a> Performance Orange là sản phẩm của PT Bayer Indonesia, thành phần chính là vitamin C, ngoài ra còn có các loại vitamin nhóm B, calci, magie, kẽm. Thuốc dùng trong trường hợp: Thiếu hụt và tăng nhu cầu vitamin C, các vitamin nhóm B và kẽm.</p>',
    isPublish: true,
    prices: [
      {
        id: 12973,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: false,
        price: 7500.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
      {
        id: 12974,
        measureUnitCode: 2,
        measureUnitName: "Tuýp",
        isSellDefault: true,
        price: 75000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00009723",
    webName: "Viên sủi Berocca Bayer bổ sung vitamin và khoáng chất (10 viên)",
    name: "BEROCCA BAYER 10V",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/IMG_1758_33831b7cab.jpg",
    slug: "thuoc/berocca-1515.html",
    brand: "Bayer",
    productRanking: 0,
    displayCode: 1,
    price: {
      id: 12974,
      measureUnitCode: 2,
      measureUnitName: "Tuýp",
      isSellDefault: true,
      price: 75000.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Tuýp 10 Viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 730,
        name: "Thuốc hô hấp",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-ho-hap",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 773,
        name: "Thuốc trị ho cảm",
        parentName: "Thuốc hô hấp",
        level: 3,
        slug: "thuoc/thuoc-ho-hap/thuoc-tri-ho-cam",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p style="text-align:justify;">Thuốc ho&nbsp;<a href="https://nhathuoclongchau.com.vn/thuoc/eugica-vien-uong-dieu-tri-ho-cam-cum-490.html">Eugica</a> xanh là sản phẩm của Dược phẩm Trường Tín, thành phần chính eucalyptol, tinh dầu gừng, menthol, tinh dầu tần, là thuốc dùng để điều trị các chứng ho, đau họng, sổ mũi, cảm cúm, làm loãng niêm dịch, làm dịu ho.</p>',
    isPublish: true,
    prices: [
      {
        id: 13886,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: true,
        price: 730.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
      {
        id: 13887,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: 7300.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
      {
        id: 13888,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: false,
        price: 73000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00010253",
    webName: "Thuốc Eugica MEGA We care điều trị ho đờm, cảm cúm, sổ mũi (10 vỉ x 10 viên)",
    name: "EUGICA XANH DHG 10X10",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/IMG_2003_e8c6321678.jpg",
    slug: "thuoc/eugica-vien-uong-dieu-tri-ho-cam-cum-490.html",
    brand: "MEGA We care",
    productRanking: 2.3676554000000003,
    displayCode: 1,
    price: {
      id: 13886,
      measureUnitCode: 8,
      measureUnitName: "Viên",
      isSellDefault: true,
      price: 730.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 10 Vỉ x 10 Viên",
  },
  {
    category: [
      {
        id: 1,
        name: "Thuốc",
        parentName: null,
        level: 1,
        slug: "thuoc",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 10,
        name: "Thuốc dị ứng",
        parentName: "Thuốc",
        level: 2,
        slug: "thuoc/thuoc-di-ung",
        isActive: true,
        searchScoring: 0,
      },
      {
        id: 750,
        name: "Thuốc chống dị ứng",
        parentName: "Thuốc dị ứng",
        level: 3,
        slug: "thuoc/thuoc-di-ung/thuoc-chong-di-ung",
        isActive: true,
        searchScoring: 0,
      },
    ],
    shortDescription:
      '<p>Thuốc <a href="https://nhathuoclongchau.com.vn/thuoc/clorpheniramin-4-200v-4228.html">Clorpheniramin</a> 4 được sản xuất bởi Công ty Cổ phần Dược Hậu Giang, với thành phần chính Chlorpheniramine maleate, là thuốc dùng để điều trị viêm mũi dị ứng, chảy nước mũi, nghẹt mũi, sổ mũi. Thuốc còn được dùng để điều trị các triệu chứng dị ứng khác như mày đay, viêm da tiếp xúc, ngứa, dị ứng do thức ăn, côn trùng cắn đốt, viêm kết mạc dị ứng và phù Quincke.</p>',
    isPublish: true,
    prices: [
      {
        id: 2371,
        measureUnitCode: 8,
        measureUnitName: "Viên",
        isSellDefault: true,
        price: 100.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 3,
        productSpecs: null,
      },
      {
        id: 2372,
        measureUnitCode: 13,
        measureUnitName: "Vỉ",
        isSellDefault: false,
        price: 2000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 2,
        productSpecs: null,
      },
      {
        id: 2373,
        measureUnitCode: 1,
        measureUnitName: "Hộp",
        isSellDefault: false,
        price: 20000.0,
        currencySymbol: "đ",
        isDefault: true,
        inventory: 31,
        isInventory: true,
        level: 1,
        productSpecs: null,
      },
    ],
    sku: "00001954",
    webName: "Thuốc Clorpheniramin 4 DHG điều trị viêm mũi dị ứng, chảy nước mũi (10 vỉ x 20 viên)",
    name: "CLORPHENIRAMIN 4MG DHG 10X20",
    image:
      "https://cdn.nhathuoclongchau.com.vn/unsafe/https://cms-prod.s3-sgn09.fptcloud.com/00001954_clorpheniramin_4_200v_6315_634e_large_7ee34183b3.jpg",
    slug: "thuoc/clorpheniramin-4-200v-4228.html",
    brand: "Dhg",
    productRanking: 0,
    displayCode: 1,
    price: {
      id: 2371,
      measureUnitCode: 8,
      measureUnitName: "Viên",
      isSellDefault: true,
      price: 100.0,
      currencySymbol: "đ",
      isDefault: true,
      inventory: 31,
      isInventory: true,
    },
    specification: "Hộp 10 vỉ x 20 viên",
  },
];
