import type { Metadata } from "next";
import "./globals.css";
import { fontInter } from "@/utils/fonts";


export const metadata: Metadata = {
  title: "NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontInter.className} suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}
