import { v4 as id } from "uuid";

export const VOCABULARY = [
  { id: id(), en: "abide by", vi: "tuân thủ / tuân theo", type: "v" },
  { id: id(), en: "agreement", vi: "sự thỏa thuận hợp đồng", type: "n" },
  { id: id(), en: "assurance", vi: "sự đảm bảo(n) / đảm bảo(v)", type: "n/v" },
  { id: id(), en: "cancellation", vi: "sự hủy bỏ / chấm dứt", type: "n" },
  { id: id(), en: "determine", vi: "xác định", type: "v" },
  { id: id(), en: "engage", vi: "tham dự", type: "v" },
  { id: id(), en: "establish", vi: "thành lập / thiết lập", type: "v" },
  { id: id(), en: "obligate", vi: "bắt buộc", type: "v" },
  { id: id(), en: "party", vi: "bên (tham gia hợp đồng)", type: "n" },
  { id: id(), en: "provision", vi: "sự cung cấp / chu cấp điều khoản", type: "n" },
  { id: id(), en: "resolve", vi: "giải quyết / quyết định", type: "v" },
  { id: id(), en: "specific", vi: "cụ thể", type: "adj" },
  { id: id(), en: "agenda", vi: "chương trình nghị sự", type: "n" },
  { id: id(), en: "innovation", vi: "sự đổi mới", type: "n" },
  { id: id(), en: "introduction", vi: "sự giới thiệu", type: "n" },
  { id: id(), en: "on-demand", vi: "theo yêu cầu", type: "n" },
  { id: id(), en: "launch something", vi: "khởi động một cái đó", type: "" },
  { id: id(), en: "attract", vi: "thu hút / hấp dẫn", type: "v" },
  { id: id(), en: "compare", vi: "so sánh / đối chiếu", type: "v" },
  { id: id(), en: "competition", vi: "sự cạnh tranh / cuộc thi", type: "n" },
  { id: id(), en: "consume", vi: "tiêu thụ / sử dụng", type: "v" },
  { id: id(), en: "convince", vi: "thuyết phục", type: "v" },
  { id: id(), en: "inspiration", vi: "nguồn cảm hứng", type: "n" },
  { id: id(), en: "market", vi: "thị trường", type: "n" },
  { id: id(), en: "persuasion", vi: "sự thuyết phục", type: "n" },
  { id: id(), en: "productive", vi: "năng suất", type: "adj" },
  { id: id(), en: "satisfaction", vi: "sự hài lòng", type: "n" },
  { id: id(), en: "currently", vi: "hiện thời / hiện nay", type: "adv" },
  { id: id(), en: "fad", vi: "mốt nhất thời", type: "n" },
  { id: id(), en: "what is cloud computing", vi: "Điện toán đám mây là gì", type: "" },
  {
    id: id(),
    en: "cloud computing is the on-demand delivery of computer power, database storage, applications and other IT resources",
    vi: "Điện toán đám mây là việc cung cấp sức mạnh tính toán, lưu trữ cơ sở dữ liệu, ứng dụng và các tài nguyên IT khác theo yêu",
    type: "",
  },
  {
    id: id(),
    en: "through a cloud services platform with pay-as-you-go pricing",
    vi: "thông qua dịch vụ đám mây với mức giá theo nhu cầu sử dụng",
    type: "",
  },
  {
    id: id(),
    en: "you can provision exactly the right type and size of computing resources you need",
    vi: "bạn có thể cung cấp chính xác loại và quy mô tài nguyên máy tính bạn cần",
    type: "",
  },
  {
    id: id(),
    en: "simple way to access servers, storage, databases and a set of application services",
    vi: "cách đơn giản truy cập vào máy chủ, bộ lưu trữ, cơ sở dữ liệu và tập hợp các dịch vụ ứng dụng.",
    type: "",
  },
  {
    id: id(),
    en: "Amazon Web Services owns and maintains the network-connected hardware required for these application services, while you provision and use what you need via a web application",
    vi: "Amazon Web Services sỡ hữu và duy trì phần cứng các kết nối mạng cần thiết cho các ứng dụng này, trong khi bạn cung cấp và sử dụng những gì bạn cần thông qua ứng dụng web",
  },
];
