import { v4 as id } from 'uuid';

export const VOCABULARY = [
  {id: id(), en: "abide by", vi: "tuân thủ / tuân theo", type: "v"},
  {id: id(), en: "agreement", vi: "sự thỏa thuận hợp đồng", type: "n"},
  {id: id(), en: "assurance", vi: "sự đảm bảo(n) / đảm bảo(v)", type: "n/v"},
  {id: id(), en: "cancellation", vi: "sự hủy bỏ / chấm dứt", type: "n"},
  {id: id(), en: "determine", vi: "xác định", type: "v"},
  {id: id(), en: "engage", vi: "tham dự", type: "v"},
  {id: id(), en: "establish", vi: "thành lập / thiết lập", type: "v"},
  {id: id(), en: "obligate", vi: "bắt buộc", type: "v"},
  {id: id(), en: "party", vi: "bên (tham gia hợp đồng)", type: "n"},
  {id: id(), en: "provision", vi: "sự cung cấp / chu cấp điều khoản", type: "n"},
  {id: id(), en: "resolve", vi: "giải quyết / quyết định", type: "v"},
  {id: id(), en: "specific", vi: "cụ thể", type: "adj"},
  {id: id(), en: "agenda", vi: "chương trình nghị sự", type: "n"},
  {id: id(), en: "innovation", vi: "sự đổi mới", type: "n"},
  {id: id(), en: "introduction", vi: "sự giới thiệu", type: "n"},
  {id: id(), en: "on-demand", vi: "theo yêu cầu", type: "n"},
  {id: id(), en: "launch something", vi: "khởi động một cái đó để bắt đầu một hoạt động", type: "n"},
  {id: id(), en: "attract", vi: "thu hút / hấp dẫn", type: "v"},
  {id: id(), en: "compare", vi: "so sánh / đối chiếu", type: "v"},
  {id: id(), en: "competition", vi: "sự cạnh tranh / cuộc thi", type: "n"},
  {id: id(), en: "consume", vi: "tiêu thụ / sử dụng", type: "v"},
  {id: id(), en: "convince", vi: "thuyết phục", type: "v"},
  {id: id(), en: "inspiration", vi: "nguồn cảm hứng", type: "n"},
  {id: id(), en: "market", vi: "thị trường", type: "n"},
  {id: id(), en: "persuasion", vi: "sự thuyết phục", type: "n"},
  {id: id(), en: "productive", vi: "năng suất", type: "adj"},
  {id: id(), en: "satisfaction", vi: "sự hài lòng", type: "n"},
  {id: id(), en: "currently", vi: "hiện thời / hiện nay", type: "adv"},
  {id: id(), en: "fad", vi: "mốt nhất thời", type: "n"},
]
