import { v4 as id } from "uuid";

export const VOCABULARY = [
  { en: "abide by", vi: "tuân thủ / tuân theo", type: "v" },
  { en: "agreement", vi: "sự thỏa thuận hợp đồng", type: "n" },
  { en: "assurance", vi: "sự đảm bảo(n) / đảm bảo(v)", type: "n/v" },
  { en: "cancellation", vi: "sự hủy bỏ / chấm dứt", type: "n" },
  { en: "determine", vi: "xác định", type: "v" },
  { en: "engage", vi: "tham dự", type: "v" },
  { en: "establish", vi: "thành lập / thiết lập", type: "v" },
  { en: "obligate", vi: "bắt buộc", type: "v" },
  { en: "party", vi: "bên (tham gia hợp đồng)", type: "n" },
  { en: "provision", vi: "sự cung cấp / chu cấp điều khoản", type: "n" },
  { en: "resolve", vi: "giải quyết / quyết định", type: "v" },
  { en: "specific", vi: "cụ thể", type: "adj" },
  { en: "agenda", vi: "chương trình nghị sự", type: "n" },
  { en: "innovation", vi: "sự đổi mới", type: "n" },
  { en: "introduction", vi: "sự giới thiệu", type: "n" },
  { en: "on-demand", vi: "theo yêu cầu", type: "n" },
  { en: "launch something", vi: "khởi động một cái đó", type: "" },
  { en: "attract", vi: "thu hút / hấp dẫn", type: "v" },
  { en: "compare", vi: "so sánh / đối chiếu", type: "v" },
  { en: "competition", vi: "sự cạnh tranh / cuộc thi", type: "n" },
  { en: "consume", vi: "tiêu thụ / sử dụng", type: "v" },
  { en: "convince", vi: "thuyết phục", type: "v" },
  { en: "inspiration", vi: "nguồn cảm hứng", type: "n" },
  { en: "market", vi: "thị trường", type: "n" },
  { en: "persuasion", vi: "sự thuyết phục", type: "n" },
  { en: "productive", vi: "năng suất", type: "adj" },
  { en: "satisfaction", vi: "sự hài lòng", type: "n" },
  { en: "currently", vi: "hiện thời / hiện nay", type: "adv" },
  { en: "fad", vi: "mốt nhất thời", type: "n" },
  { en: "and", vi: "và", type: "conj" },
  { en: "or", vi: "hoặc", type: "conj" },
  { en: "water", vi: "nước", type: "n" },
  { en: "go", vi: "di chuyển", type: "v" },
  { en: "tea", vi: "trà", type: "n" },
  { en: "coffee", vi: "cà phê", type: "n" },
  { en: "hello", vi: "chào", type: "v" },
  { en: "goodbye", vi: "tạm biệt", type: "v" },
  { en: "sea", vi: "nước biển", type: "n" },
  { en: "good morning", vi: "chào buổi sáng", type: "v" },
  { en: "good afternoon", vi: "chào buổi trưa", type: "v" },
  { en: "good evening", vi: "chào buổi tối", type: "v" },
  { en: "good night", vi: "chúc ngủ ngon", type: "v" },
  { en: "morning", vi: "buổi sáng", type: "n" },
  { en: "afternoon", vi: "buổi trưa", type: "n" },
  { en: "evening", vi: "buổi tối", type: "n" },
  { en: "night", vi: "ngủ ngon", type: "n" },
  { en: "please", vi: "làm ơn", type: "v" },
  { en: "thank you", vi: "cảm ơn", type: "v" },
  { en: "my", vi: "tôi", type: "pron" },
  { en: "name", vi: "tên", type: "n" },
  { en: "wet", vi: "ướt", type: "adj" },
  { en: "with", vi: "bằng/với", type: "conj" },
  { en: "you", vi: "bạn", type: "pron" },
  { en: "milk", vi: "sữa", type: "n" },
  { en: "yes", vi: "có", type: "pron" },
  { en: "no", vi: "không", type: "pron" },
  { en: "for", vi: "cho", type: "conj" },
  { en: "look", vi: "xem", type: "v" },
  { en: "like", vi: "thích", type: "v" },
  { en: "sugar", vi: "đường", type: "n" },
  { en: "or", vi: "hoặc", type: "conj" },
  { en: "right", vi: "chính xác", type: "adj" },
  { en: "wrong", vi: "sai", type: "adj" },
  { en: "yell", vi: "la", type: "v" },
  { en: "part", vi: "phần, bộ phận, nơi", type: "n" },
  { en: "teacher", vi: "giáo viên", type: "n" },
  { en: "student", vi: "học sinh", type: "n" },
  { en: "math", vi: "môn toán", type: "n" },
  { en: "science", vi: "môn khoa học", type: "n" },
  { en: "history", vi: "môn lịch sử", type: "n" },
  { en: "find", vi: "tìm kiếm", type: "v" },
  { en: "excuse me", vi: "làm ơn cho tôi", type: "v" },
  { en: "driver", vi: "tài xế", type: "n" },
  { en: "sat", vi: "đã ngồi", type: "v" },
  { en: "book", vi: "sách", type: "n" },
  { en: "computer", vi: "máy tính", type: "n" },
  { en: "then", vi: "sau đó", type: "conj" },
  { en: "has", vi: "có từng", type: "conj" },
  { en: "this", vi: "đây, điều này, việc này", type: "pron" },
  { en: "camera", vi: "máy ảnh", type: "n" },
  { en: "nose", vi: "cái mũi", type: "n" },
  { en: "eye", vi: "cái mắt", type: "n" },
  { en: "phone", vi: "điện thoại", type: "n" },
  { en: "your", vi: "của bạn, của các bạn", type: "pron" },
  { en: "new", vi: "mới", type: "adj" },
  { en: "old", vi: "cũ", type: "adj" },
  { en: "red", vi: "màu đỏ", type: "adj" },
  { en: "blue", vi: "màu xanh", type: "adj" },
  { en: "green", vi: "màu xanh lá", type: "adj" },
  { en: "yellow", vi: "màu vàng", type: "adj" },
  { en: "black", vi: "màu đen", type: "adj" },
  { en: "white", vi: "màu trắng", type: "adj" },
  { en: "orange", vi: "màu cam", type: "adj" },
  { en: "pink", vi: "màu hồng", type: "adj" },
  { en: "purple", vi: "màu tím", type: "adj" },
  { en: "brown", vi: "màu cam", type: "adj" },
  { en: "gray", vi: "màu xám", type: "adj" },
  { en: "silver", vi: "màu bạc", type: "adj" },
  { en: "bag", vi: "cái túi", type: "n" },
  { en: "coat", vi: "cái áo khoác", type: "n" },
  { en: "shirt", vi: "cái áo sơ mi", type: "n" },
  { en: "pants", vi: "cái quần", type: "n" },
  { en: "shoes", vi: "cái dép", type: "n" },
  { en: "met", vi: "đã gặp", type: "v" },
  { en: "meet", vi: "gặp mặt", type: "v" },
  { en: "share", vi: "chia sẻ", type: "v" },
  { en: "well", vi: "hay, ổn, tốt", type: "" },
  { en: "wife", vi: "vợ", type: "n" },
  { en: "husband", vi: "chồng", type: "n" },
  { en: "she", vi: "cô ấy, bà ấy", type: "" },
  { en: "he", vi: "anh ấy, ông ấy", type: "" },
  { en: "son", vi: "con trai", type: "n" },
  { en: "daughter", vi: "con gái", type: "n" },
  { en: "brother", vi: "anh, em trai", type: "n" },
  { en: "sister", vi: "chị, em gái", type: "n" },
  { en: "boyfriend", vi: "bạn trai", type: "n" },
  { en: "girlfriend", vi: "bạn gái", type: "n" },
  { en: "same", vi: "cùng, giống nhau, như nhau", type: "conj" },
  { en: "our", vi: "của chúng tôi, của chúng ta", type: "pron" },
  { en: "date", vi: "ngày, hẹn hò", type: "n" },
  { en: "friend", vi: "bạn bè", type: "n" },
  { en: "smart", vi: "thông minh", type: "adj" },
  { en: "doctor", vi: "bác sĩ", type: "n" },
  { en: "very", vi: "quá, rất", type: "" },
  { en: "tall", vi: "cao, cao lớn", type: "" },
  // Mua sắm ở cửa hàng
  { en: "shop", vi: "cửa hàng", type: "n" },
  { en: "buy", vi: "mua", type: "v" },
  { en: "sell", vi: "bán", type: "v" },
  { en: "price", vi: "giá", type: "n" },
  { en: "expensive", vi: "đắt", type: "adj" },
  { en: "cheap", vi: "rẻ", type: "adj" },
  { en: "discount", vi: "giảm giá", type: "n" },
  { en: "cash", vi: "tiền mặt", type: "n" },
  { en: "credit card", vi: "thẻ tín dụng", type: "n" },
  { en: "size", vi: "kích cỡ", type: "n" },
  { en: "color", vi: "màu sắc", type: "n" },
  { en: "try on", vi: "thử đồ", type: "v" },
  { en: "fitting room", vi: "phòng thử đồ", type: "n" },
  { en: "customer", vi: "khách hàng", type: "n" },
  { en: "shop assistant", vi: "nhân viên bán hàng", type: "n" },
  { en: "receipt", vi: "hóa đơn", type: "n" },
  { en: "change", vi: "tiền thừa", type: "n" },
  { en: "sale", vi: "giảm giá", type: "n" },
  { en: "refund", vi: "hoàn tiền", type: "n" },
  { en: "department store", vi: "cửa hàng bách hóa", type: "n" },
  { en: "grocery store", vi: "cửa hàng tạp hóa", type: "n" },
  { en: "clothing store", vi: "cửa hàng quần áo", type: "n" },
  { en: "Can I try this on?", vi: "Tôi có thể thử cái này không?", type: "phrase" },
  {
    en: "Do you have this in a different size/color?",
    vi: "Bạn có cái này với kích cỡ/màu sắc khác không?",
    type: "phrase",
  },
  { en: "How much is this?", vi: "Cái này giá bao nhiêu?", type: "phrase" },
  { en: "I'll take it.", vi: "Tôi sẽ lấy nó.", type: "phrase" },
  { en: "I'm just looking.", vi: "Tôi chỉ xem qua thôi.", type: "phrase" },
  {
    en: "Excuse me, do you sell [product]?",
    vi: "Xin lỗi, bạn có bán [sản phẩm] không?",
    type: "phrase",
  },
  {
    en: "Where can I find the [product]?",
    vi: "Tôi có thể tìm thấy [sản phẩm] ở đâu không?",
    type: "phrase",
  },
  {
    en: "Do you have this in a smaller/larger size?",
    vi: "Bạn có cái này với kích cỡ nhỏ hơn/lớn hơn không?",
    type: "phrase",
  },
  {
    en: "Do you have this in a different color?",
    vi: "Bạn có cái này với màu sắc khác không?",
    type: "phrase",
  },
  { en: "How much is this?", vi: "Cái này giá bao nhiêu?", type: "phrase" },
  { en: "Is this on sale?", vi: "Cái này đang được giảm giá phải không?", type: "phrase" },
  { en: "I will take this", vi: "Tôi sẽ lấy cái này", type: "phrase" },
  {
    en: "Can I pay by credit card?",
    vi: "Tôi có thể thanh toán bằng thẻ tín dụng không?",
    type: "phrase",
  },
  { en: "Can I pay by cash?", vi: "Tôi có thể thanh toán bằng tiền mặt không?", type: "phrase" },

  // Dùng tính từ sở hữu
  { en: "my", vi: "của tôi", type: "pron" },
  { en: "your", vi: "của bạn", type: "pron" },
  { en: "his", vi: "của anh ấy", type: "pron" },
  { en: "her", vi: "của cô ấy", type: "pron" },
  { en: "its", vi: "của nó", type: "pron" },
  { en: "our", vi: "của chúng tôi", type: "pron" },
  { en: "their", vi: "của họ", type: "pron" },
  { en: "mine", vi: "của tôi", type: "pron" },
  { en: "yours", vi: "của bạn (nhiều)", type: "pron" },
  { en: "hers", vi: "của cô ấy (nhiều)", type: "pron" },
  { en: "ours", vi: "của chúng tôi (nhiều)", type: "pron" },
  { en: "theirs", vi: "của họ (nhiều)", type: "pron" },
  {
    en: "That's mine/yours/his/hers/ours/theirs.",
    vi: "Đó là của tôi/bạn/anh ấy/cô ấy/chúng tôi/họ.",
    type: "phrase",
  },
  { en: "Is this yours?", vi: "Đây có phải của bạn không?", type: "phrase" },
  { en: "Whose book is this?", vi: "Cuốn sách này của ai?", type: "phrase" },

  // Trò chuyện đại học
  { en: "university", vi: "trường đại học", type: "n" },
  { en: "student", vi: "sinh viên", type: "n" },
  { en: "professor", vi: "giáo sư", type: "n" },
  { en: "class", vi: "lớp học", type: "n" },
  { en: "exam", vi: "bài kiểm tra", type: "n" },
  { en: "homework", vi: "bài tập về nhà", type: "n" },
  { en: "library", vi: "thư viện", type: "n" },
  { en: "study", vi: "học", type: "v" },
  { en: "graduate", vi: "tốt nghiệp", type: "v" },
  { en: "major", vi: "chuyên ngành", type: "n" },
  { en: "campus", vi: "khuôn viên trường", type: "n" },
  { en: "dorm", vi: "ký túc xá", type: "n" },
  { en: "lecture", vi: "bài giảng", type: "n" },
  { en: "semester", vi: "học kỳ", type: "n" },
  { en: "assignment", vi: "bài tập", type: "n" },
  { en: "research", vi: "nghiên cứu", type: "n" },
  { en: "degree", vi: "bằng cấp", type: "n" },
  { en: "What's your major?", vi: "Chuyên ngành của bạn là gì?", type: "phrase" },
  {
    en: "I'm a freshman/sophomore/junior/senior.",
    vi: "Tôi là sinh viên năm nhất/năm hai/năm ba/năm cuối.",
    type: "phrase",
  },
  {
    en: "I have a class at [hour] in [classroom].",
    vi: "Tôi có một lớp học lúc [giờ] ở [phòng học].",
    type: "phrase",
  },
  {
    en: "The library is a great place to study.",
    vi: "Thư viện là một nơi tuyệt vời để học tập.",
    type: "phrase",
  },
  {
    en: "I'm really struggling with this class.",
    vi: "Tôi thực sự đang gặp khó khăn với lớp học này.",
    type: "phrase",
  },
  { en: "This is my book.", vi: "Đây là cuốn sách của tôi.", type: "phrase" },
  { en: "Is that your car?", vi: "Đây là chiếc xe của bạn không?", type: "phrase" },
  {
    en: "His house is bigger than hers.",
    vi: "Nhà của anh ấy lớn hơn nhà của cô ấy.",
    type: "phrase",
  },
  { en: "We brought our own food.", vi: "Chúng tôi đã tự mang đồ ăn theo", type: "phrase" },

  // Nói về đồ vật
  { en: "thing", vi: "đồ vật", type: "n" },
  { en: "object", vi: "vật thể", type: "n" },
  { en: "big", vi: "to", type: "adj" },
  { en: "small", vi: "nhỏ", type: "adj" },
  { en: "heavy", vi: "nặng", type: "adj" },
  { en: "light", vi: "nhẹ", type: "adj" },
  { en: "long", vi: "dài", type: "adj" },
  { en: "short", vi: "ngắn", type: "adj" },
  { en: "round", vi: "tròn", type: "adj" },
  { en: "square", vi: "vuông", type: "adj" },
  { en: "shape", vi: "hình dạng", type: "n" },
  { en: "material", vi: "chất liệu", type: "n" },
  { en: "soft", vi: "mềm", type: "adj" },
  { en: "hard", vi: "cứng", type: "adj" },
  { en: "smooth", vi: "trơn", type: "adj" },
  { en: "rough", vi: "gồ ghề", type: "adj" },
  { en: "transparent", vi: "trong suốt", type: "adj" },
  { en: "opaque", vi: "mờ đục", type: "adj" },
  {
    en: "It's made of [chất liệu].",
    vi: "Nó được làm bằng [chất liệu].",
    type: "phrase",
  },
  { en: "It's a bit heavy/light.", vi: "Nó hơi nặng/nhẹ.", type: "phrase" },
  { en: "It's very old/new.", vi: "Nó rất cũ/mới.", type: "phrase" },
  {
    en: "What's this called in English?",
    vi: "Cái này tiếng Anh gọi là gì?",
    type: "phrase",
  },

  // Miêu tả người quen
  { en: "friend", vi: "bạn", type: "n" },
  { en: "family", vi: "gia đình", type: "n" },
  { en: "kind", vi: "tốt bụng", type: "adj" },
  { en: "friendly", vi: "thân thiện", type: "adj" },
  { en: "funny", vi: "vui tính", type: "adj" },
  { en: "intelligent", vi: "thông minh", type: "adj" },
  { en: "beautiful", vi: "xinh đẹp", type: "adj" },
  { en: "handsome", vi: "đẹp trai", type: "adj" },
  { en: "tall", vi: "cao", type: "adj" },
  { en: "short", vi: "ngắn", type: "adj" },
  { en: "personality", vi: "tính cách", type: "n" },
  { en: "appearance", vi: "ngoại hình", type: "n" },
  { en: "generous", vi: "hào phóng", type: "adj" },
  { en: "optimistic", vi: "lạc quan", type: "adj" },
  { en: "creative", vi: "sáng tạo", type: "adj" },
  { en: "patient", vi: "kiên nhẫn", type: "adj" },
  { en: "shy", vi: "nhút nhát", type: "adj" },
  { en: "outgoing", vi: "hướng ngoại", type: "adj" },
  {
    en: "He/She is very kind/friendly/funny.",
    vi: "Anh ấy/Cô ấy rất tốt bụng/thân thiện/vui tính.",
    type: "phrase",
  },
  {
    en: "We've been friends since [thời gian].",
    vi: "Chúng tôi đã là bạn từ [thời gian].",
    type: "phrase",
  },
  {
    en: "He/She is a great person.",
    vi: "Anh ấy/Cô ấy là một người tuyệt vời.",
    type: "phrase",
  },
  {
    en: "I really admire him/her.",
    vi: "Tôi thực sự ngưỡng mộ anh ấy/cô ấy.",
    type: "phrase",
  },

  // Gọi đồ ăn uống
  { en: "menu", vi: "thực đơn", type: "n" },
  { en: "order", vi: "gọi món", type: "v" },
  { en: "food", vi: "món ăn", type: "n" },
  { en: "drink", vi: "đồ uống", type: "n" },
  { en: "water", vi: "nước lọc", type: "n" },
  { en: "tea", vi: "trà", type: "n" },
  { en: "coffee", vi: "cà phê", type: "n" },
  { en: "juice", vi: "nước ép", type: "n" },
  { en: "beer", vi: "bia", type: "n" },
  { en: "wine", vi: "rượu", type: "n" },
  { en: "soup", vi: "súp", type: "n" },
  { en: "salad", vi: "salad", type: "n" },
  { en: "bread", vi: "bánh mì", type: "n" },
  { en: "rice", vi: "cơm", type: "n" },
  { en: "noodles", vi: "mì", type: "n" },
  { en: "chicken", vi: "gà", type: "n" },
  { en: "beef", vi: "bò", type: "n" },
  { en: "pork", vi: "thịt lợn", type: "n" },
  { en: "fish", vi: "cá", type: "n" },
  { en: "vegetables", vi: "rau củ", type: "n" },
  { en: "fruit", vi: "hoa quả", type: "n" },
  { en: "dessert", vi: "món tráng miệng", type: "n" },
  {
    en: "Could I see the menu, please?",
    vi: "Cho tôi xem thực đơn được không?",
    type: "phrase",
  },
  { en: "I'll have the [food].", vi: "Tôi muốn gọi món [món ăn].", type: "phrase" },
  {
    en: "Could I get another [beverage], please?",
    vi: "Cho tôi thêm một [đồ uống] nữa được không?",
    type: "phrase",
  },
  { en: "The bill, please.", vi: "Cho tôi xin hóa đơn.", type: "phrase" },

  // Giới thiệu bản thân
  { en: "name", vi: "tên", type: "n" },
  { en: "age", vi: "tuổi", type: "n" },
  { en: "from", vi: "đến từ", type: "prep" },
  { en: "live in", vi: "sống ở", type: "v" },
  { en: "work", vi: "làm việc", type: "v" },
  { en: "study", vi: "học tập", type: "v" },
  { en: "hobbies", vi: "sở thích", type: "n" },
  { en: "Hi, my name is [name].", vi: "Xin chào, tôi tên là [tên].", type: "phrase" },
  { en: "I'm [age] years old.", vi: "Tôi [tuổi] tuổi.", type: "phrase" },
  { en: "I'm from", vi: "Tôi đến từ", type: "phrase" },
  {
    en: "I'm a [profession/position].",
    vi: "Tôi là một [nghề nghiệp/chức vụ].",
    type: "phrase",
  },
  {
    en: "In my free time, I like to [hobbies].",
    vi: "Trong thời gian rảnh rỗi, tôi thích [sở thích].",
    type: "phrase",
  },

  // Miêu tả ý thích
  { en: "like", vi: "thích", type: "v" },
  { en: "love", vi: "yêu thích", type: "v" },
  { en: "enjoy", vi: "thưởng thức", type: "v" },
  { en: "interested in", vi: "quan tâm đến", type: "adj" },
  { en: "favorite", vi: "yêu thích nhất", type: "adj" },
  {
    en: "I really like/love [food/activity].",
    vi: "Tôi rất thích/yêu thích [món ăn/hoạt động].",
    type: "phrase",
  },
  {
    en: "I'm not a big fan of [food/activity].",
    vi: "Tôi không phải là người thích [món ăn/hoạt động].",
    type: "phrase",
  },

  // Gọi món nhà hàng (nói hiện tại đơn)
  { en: "I want", vi: "Tôi muốn", type: "phrase" },
  { en: "I'd like", vi: "Tôi muốn", type: "phrase" },
  { en: "Can I have", vi: "Cho tôi", type: "phrase" },
  { en: "please", vi: "làm ơn", type: "adv" },
  {
    en: "He/She wants the [food].",
    vi: "Anh ấy/Cô ấy muốn món [món ăn].",
    type: "phrase",
  },
  { en: "We'd like to order, please.", vi: "Chúng tôi muốn gọi món.", type: "phrase" },
  { en: "Do you have any [food]?", vi: "Bạn có [món ăn] nào không?", type: "phrase" },

  // Đặt câu hỏi
  { en: "What", vi: "Cái gì", type: "question" },
  { en: "Where", vi: "Ở đâu", type: "question" },
  { en: "When", vi: "Khi nào", type: "question" },
  { en: "Why", vi: "Tại sao", type: "question" },
  { en: "How", vi: "Như thế nào", type: "question" },
  { en: "Who", vi: "Ai", type: "question" },
  { en: "What's your name?", vi: "Tên bạn là gì?", type: "phrase" },
  { en: "Where are you from?", vi: "Bạn đến từ đâu?", type: "phrase" },
  { en: "How old are you?", vi: "Bạn bao nhiêu tuổi?", type: "phrase" },
  { en: "What do you do?", vi: "Bạn làm nghề gì?", type: "phrase" },
  { en: "What are your hobbies?", vi: "Sở thích của bạn là gì?", type: "phrase" },
];
