export const VOCABULARY = [
  { en: "I get up", vi: "Tôi thức dậy", type: "phrase" },
  { en: "I'm yawning", vi: "Tôi đang ngáp", type: "phrase" },
  { en: "I'm sleepy", vi: "Tôi buồn ngủ", type: "phrase" },
  { en: "I wash my face", vi: "Tôi rửa mặt", type: "phrase" },
  { en: "The water is cold", vi: "Nước rất lạnh", type: "phrase" },
  { en: "I can't open my eyes", vi: "Tôi không thể mở mắt", type: "phrase" },
  { en: "I drink some milk", vi: "Tôi uống một chút sữa", type: "phrase" },
  { en: "I wipe my mouth", vi: "Tôi lau miệng", type: "phrase" },
  { en: "I take off my pajamas", vi: "Tôi cởi đồ ngủ ra", type: "phrase" },
  { en: "I put on my clothes", vi: "Tôi mặc quần áo", type: "phrase" },
  { en: "I put on my pink blouse", vi: "Tôi mặc áo choàng hồng", type: "phrase" },
  { en: "I put on my green skirt", vi: "Tôi mặc váy xanh", type: "phrase" },
  { en: "This is my favorite skirt", vi: "Đây là chiếc váy yêu thích của tôi", type: "phrase" },
  { en: "Do I look pretty?", vi: "Nhìn tôi có đẹp không?", type: "phrase" },
  {
    en: "I look at some pretty flowers",
    vi: "Tôi nhìn thấy vài bông hoa xinh xắn",
    type: "phrase",
  },
  { en: "They smell good", vi: "Chúng có mùi thơm", type: "phrase" },
  { en: "Mommy takes care of these flowers", vi: "Mẹ chăm sóc những bông hoa này", type: "phrase" },
  {
    en: "I pour some miso soup over the rice",
    vi: "Tôi đổ một ít súp miso lên cơm",
    type: "phrase",
  },
  { en: "Mommy doesn't like me doing so", vi: "Mẹ không thích tôi làm như vậy", type: "phrase" },
  { en: "I spill my miso soup", vi: "Tôi làm đổ súp miso của tôi", type: "phrase" },
  { en: "I walk to school", vi: "Tôi đi bộ đến trường", type: "phrase" },
  { en: "I wear my green shoes", vi: "Tôi mang đôi giày xanh lá cây", type: "phrase" },
  { en: "I water the flowers", vi: "Tôi tưới hoa", type: "phrase" },
  { en: "Tulips are colorful", vi: "Hoa tulip có nhiều màu sắc", type: "phrase" },
  { en: "I use my watering can", vi: "Tôi dùng bình tưới cây", type: "phrase" },
  { en: "I water the garden", vi: "Tôi tưới nước cho khu vườn", type: "phrase" },
  { en: "It's hot today", vi: "Hôm nay trời nóng", type: "phrase" },
  { en: "I swim in the ocean", vi: "Tôi bơi ở biển", type: "phrase" },
  { en: "I wear my swimsuit and swim cap", vi: "Tôi mặc bộ đồ bơi và mũ tắm", type: "phrase" },
  { en: "I can swim very well", vi: "Tôi có thể bơi rất giỏi", type: "phrase" },
  { en: "I eat ice cream", vi: "Tôi ăn kem", type: "phrase" },
  { en: "I'm hot", vi: "Tôi thấy nóng", type: "phrase" },
  { en: "I turn on the water", vi: "Tôi mở nước", type: "phrase" },
  { en: "I let the water run", vi: "Tôi cho nước chảy", type: "phrase" },
  { en: "I look at the water running", vi: "Tôi nhìn nước chảy", type: "phrase" },
  { en: "I turn off the water", vi: "Tôi khóa nước lại", type: "phrase" },
  { en: "I save water", vi: "Tôi tiết kiệm nước", type: "phrase" },
  { en: "Water is important", vi: "Nước rất quan trọng", type: "phrase" },
  {
    en: "I put some detergent in the washing machine",
    vi: "Tôi đổ một chút xà phòng vào máy giặt",
    type: "phrase",
  },
  { en: "I put in too much soap", vi: "Tôi lỡ đổ quá nhiều xà phòng", type: "phrase" },
  { en: "I do the laundry", vi: "Tôi giặt đồ", type: "phrase" },
  { en: "I put dirty clothes in", vi: "Tôi cho quần áo bẩn vào", type: "phrase" },
  { en: "There are so many dirty clothes", vi: "Có rất nhiều quần áo bẩn", type: "phrase" },
  {
    en: "I shouldn't put many clothes in",
    vi: "Tôi không nên cho nhiều quần áo vào",
    type: "phrase",
  },
  { en: "I turn on the switch", vi: "Tôi bật công tắc", type: "phrase" },
  { en: "The washing machine starts working", vi: "Máy giặt bắt đầu hoạt động", type: "phrase" },
  { en: "It's noisy", vi: "Thật là ồn ào", type: "phrase" },
  { en: "I wash some clothes by myself", vi: "Tôi giặt một vài bộ quần áo", type: "phrase" },
  { en: "I make soap bubbles", vi: "Tôi tạo bọt xà phòng", type: "phrase" },
  { en: "I rinse the clothes", vi: "Tôi giữ quần áo", type: "phrase" },
  { en: "They are getting clean", vi: "Chúng đang sạch dần", type: "phrase" },
  { en: "I have to dry the water", vi: "Tôi phải vắt nước", type: "phrase" },
  { en: "I talk with mommy", vi: "Tôi nói chuyện với mẹ", type: "phrase" },
  { en: "I carry the laundry basket", vi: "Tôi mang giỏ giặt", type: "phrase" },
  { en: "I help mommy", vi: "Tôi giúp mẹ", type: "phrase" },
  { en: "I hang the laundry outside", vi: "Tôi treo đồ giặt ra ngoài", type: "phrase" },
  { en: "I'm standing on the stool", vi: "Tôi đang đứng trên ghế đẩu", type: "phrase" },
  { en: "I put clothespins on the clothes", vi: "Tôi kẹp quần áo", type: "phrase" },
  { en: "I smooth the clothes down", vi: "Tôi kéo xống.", type: "phrase" },
  { en: "It will remove the wrinkles", vi: "Nó sẽ loại bỏ nếp nhăn.", type: "phrase" },
  { en: "I'm standing on my tiptoes", vi: "Tôi đang kiễng chân lên.", type: "phrase" },
  { en: "I hand a ladle to mommy", vi: "Tôi đưa cái muỗng cho mẹ.", type: "phrase" },
  { en: "I help mommy cook", vi: "Tôi giúp mẹ nấu ăn.", type: "phrase" },
  { en: "We make lunch together", vi: "Chúng tôi làm bữa trưa cùng nhau.", type: "phrase" },
  { en: "I make noodles", vi: "Tôi làm mì.", type: "phrase" },
  { en: "I make the dough thinner", vi: "Tôi cán bột mỏng hơn.", type: "phrase" },
  { en: "I use the rolling pin", vi: "Tôi sử dụng cái cán.", type: "phrase" },
  { en: "I leave the table", vi: "Tôi rời khỏi bàn.", type: "phrase" },
  { en: "I finish setting the table", vi: "Tôi dọn bàn xong.", type: "phrase" },
  { en: "Lunch is ready", vi: "Bữa trưa đã sẵn sàng.", type: "phrase" },
  { en: "I finish my bowl", vi: "Tôi đã ăn xong bát của tôi.", type: "phrase" },
  { en: "It's very tasty", vi: "Nó rất ngon.", type: "phrase" },
  { en: "I like noodles", vi: "Tôi thích mì.", type: "phrase" },
  { en: "I take a nap", vi: "Tôi ngủ trưa.", type: "phrase" },
  { en: "My cat takes a nap too", vi: "Con mèo của tôi cũng ngủ trưa.", type: "phrase" },
  { en: "I put a blanket on my tummy", vi: "Tôi đắp chăn lên bụng.", type: "phrase" },
  { en: "I go into my room", vi: "Tôi vào phòng của tôi.", type: "phrase" },
  { en: "I open the door", vi: "Tôi mở cửa.", type: "phrase" },
  {
    en: "I have a soccer ball in my room",
    vi: "Tôi có một quả bóng đá trong phòng của tôi.",
    type: "phrase",
  },
  { en: "I change my shirt", vi: "Tôi thay đồ sơ mi.", type: "phrase" },
  {
    en: "It's a purple shirt with black stripes",
    vi: "Đó là một chiếc áo sơ mi màu tím có sọc đen.",
    type: "phrase",
  },
  { en: "I love this clean shirt", vi: "Tôi rất thích đồ sơ mi sạch sẽ này.", type: "phrase" },
];
